name: Create Release and Publish to PyPI

on:
  release:
    types:
        - released
        - prereleased

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install poetry
        run: pip install poetry
        shell: bash

      - name: Set Package Version
        shell: bash
        run: |
          sed -i -r 's/__version__ *= *".*"/__version__ = "${{ github.event.release.tag_name }}"/g' src/dbt_argo/__init__.py
          sed -i '0,/version =.*/s//version = "'"${{ github.event.release.tag_name }}"'"/' ./pyproject.toml

      - name: Add and Commit Version
        shell: bash
        run: |
          git add src ./pyproject.toml
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -m "Change version to ${{ github.event.release.tag_name }}" --allow-empty
          git push origin HEAD:main
        
      - name: Install package
        shell: bash
        run: |
          poetry install --no-root

      - name: Build and Publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish --build
        shell: bash
